### ISSUE TITLE
easy bug 

### ISSUE THREAD

**Issue by grummbunger** [cjlarose/weiqi.js#35] opened 2020-10-24 20:59 UTC
i got a bug, should be real easy to fix. easier to show as it involves a few stones. i present 2 reproduceable situations and a situation that is almost the same but has no bug.

it is 

```
01234567
1*******
2b******
3*b*****
4bw*****
5*w*****
6ww*****
7*******
```

b play at 1,5
w play at 1,3 kills 2 black
b play at 1,4 thinks it is a ko and wont place.

i uploaded an sgf with 2 examples and a non bugged situation to

http://eidogo.com/#4ym5q30VY

**Comment by cjlarose** [comment] 2020-10-26 17:25
Thanks for the bug report. This is interesting. So I think the first reproducible case you give is actually a violation of what's called [positional superko][0]. In this case, when black plays at 1,4, the board is in the same position as the starting condition. The fact that the library uses positional superko instead of the more traditional ko rule is documented in the README, so I wouldn't 100% call this a bug, but I think you're right that it's a bit unexpected since most popular rulesets don't use positional superko.

I think maybe a _feature request_ for implementing the "simple ko" rule makes sense. Maybe when the user constructs a new game, they can choose which Ko rule they want, and the "simple ko" rule should probably be the default.

[0]: https://senseis.xmp.net/?Superko

**Comment by grummbunger** [comment] 2020-10-26 19:16
Ahhhhhh. We learn each day. Yeah I'm not sure any games or apps use the superko (I did not know that before very good to know)  I then yes request your suggestion in this case, in the meantime I will note on my page (still unpublished) and make my ai watch not to play that for now (perhaps I'll set a flag for allowing or dissallowing it)

I still have not yet generated a true 1000 year ko.

I think the board also needs an undo.

I am going to soon try to use it multiple times at once. Should be interesting.


⁣Get TypeApp for Android ​

**Comment by cjlarose** [comment] 2020-10-26 20:51
I'll close this issue and track the implementation of a different ko rule option in #36

Thanks for the feedback and keep it coming!

**Closed as completed by cjlarose** 2020-10-26 20:51 UTC
